### ISSUE TITLE
App: Pagar.me

### ISSUE THREAD

**Issue by leomp12** [ecomplus/app-pagarme#1]
- [x] List payments;
- [x] Create transaction;
- [x] Postback;
- [x] Admin settings;
- [x] Ícones para o Market e checkout e descrição em md;
- [x] Últimos testes e publicação para o Market;

**Comment by leomp12** [comment]
@vitorrgg preciso da sua ajuda aqui de novo com os ícones, mesmo caso do MP.

**Comment by vitorrgg** [comment]
![pagarme](https://user-images.githubusercontent.com/35348281/80384243-04235200-887b-11ea-8b15-23aa95d63881.png)
![pagarmecard](https://user-images.githubusercontent.com/35348281/80384253-0685ac00-887b-11ea-93ac-3f8d7a7f2e1d.png)

**Comment by leomp12** [comment]
@vitorrgg Pagar.me aceita todas essas bandeiras mesmo? Lembro que não aceitava tudo isso antes...
@matheusgnreis

**Comment by leomp12** [comment]
@vitorrgg e era mais importante ter o selinho de seguro que o logo do Pagar.me, tipo do Wirecard:

![](https://e-com.club/mass/ftp/others/credito-wirecard.png)

**Comment by vitorrgg** [comment]
Entendi que esse PCI era só no wirecard, vou colocar também então. Aceita essa e algumas outras de acordo com isso [aqui](https://pagarme.zendesk.com/hc/pt-br/articles/204766289-Quais-bandeiras-de-cart%C3%A3o-de-cr%C3%A9dito-o-Pagar-me-aceita-).

**Comment by leomp12** [comment]
@vitorrgg todos os intermediadores precisam de certificação PCI DSS pra transação com cartão, em muitos casos o selo verde com o logo do PCI é mais útil do que a marca do intermediador que nem sempre é conhecida pelo cliente final.

**Comment by leomp12** [comment]
https://app.e-com.plus/#/apps/edit/117391

**Comment by vitorrgg** [comment]
![pagarmecard](https://user-images.githubusercontent.com/35348281/80546011-ff4dc380-898a-11ea-9f23-980149e261f8.png)
