### ISSUE TITLE
Aplicando desconto no parcelamento mesmo com a opção nao habilitada

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/app-pagarme#85]
**Descreva o bug**
Aparentemente, o app verifica se há desconto configurado, mas não por forma de pagamento, logo ao calcular as parcelas, é feito com amount com desconto e assim, gera as parcelas com desconto e 1x, sem desconto, mesmo não sendo configurado.

**Comment by matheusgnreis** [comment]
https://github.com/ecomplus/app-pagarme/pull/84

**Comment by leomp12** [comment]
Que opção? Nem existia essa opção 😄
